// Code generated by Slice Machine. DO NOT EDIT.

import type * as prismic from "@prismicio/client";

type Simplify<T> = { [KeyType in keyof T]: T[KeyType] };

/**
 * Content for Footer documents
 */
interface FooterDocumentData {
  /**
   * Phone Number field in *Footer*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: footer.phone_number
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  phone_number: prismic.KeyTextField;

  /**
   * Optional Phone Number 1 field in *Footer*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: footer.optional_phone_number_1
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  optional_phone_number_1: prismic.KeyTextField;

  /**
   * Optional Phone Number 2 field in *Footer*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: footer.optional_phone_number_2
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  optional_phone_number_2: prismic.KeyTextField;

  /**
   * Email field in *Footer*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: footer.email
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  email: prismic.KeyTextField;

  /**
   * Optional Email 1 field in *Footer*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: footer.optional_email_1
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  optional_email_1: prismic.KeyTextField;

  /**
   * Optional Email 2 field in *Footer*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: footer.optional_email_2
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  optional_email_2: prismic.KeyTextField;

  /**
   * Address field in *Footer*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: footer.address
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  address: prismic.KeyTextField;

  /**
   * Optional Address 1 field in *Footer*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: footer.optional_address_1
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  optional_address_1: prismic.KeyTextField;

  /**
   * Optional Address 2 field in *Footer*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: footer.optional_address_2
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  optional_address_2: prismic.KeyTextField;

  /**
   * Facebook field in *Footer*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: footer.facebook
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  facebook: prismic.LinkField;

  /**
   * Instagram field in *Footer*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: footer.instagram
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  instagram: prismic.LinkField;

  /**
   * Twitter field in *Footer*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: footer.twitter
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  twitter: prismic.LinkField;
}

/**
 * Footer document from Prismic
 *
 * - **API ID**: `footer`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type FooterDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<FooterDocumentData>,
    "footer",
    Lang
  >;

type LandingPageDocumentDataSlicesSlice =
  | ImageSlice
  | PageDescriptionSlice
  | TitleSlice;

/**
 * Content for Landing Page documents
 */
interface LandingPageDocumentData {
  /**
   * Slice Zone field in *Landing Page*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: landing_page.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<LandingPageDocumentDataSlicesSlice> /**
   * Meta Description field in *Landing Page*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: landing_page.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */;
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *Landing Page*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: landing_page.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  meta_image: prismic.ImageField<never>;

  /**
   * Meta Title field in *Landing Page*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: landing_page.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_title: prismic.KeyTextField;
}

/**
 * Landing Page document from Prismic
 *
 * - **API ID**: `landing_page`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type LandingPageDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<LandingPageDocumentData>,
    "landing_page",
    Lang
  >;

/**
 * Content for Publication documents
 */
interface PublicationDocumentData {
  /**
   * Cite field in *Publication*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: publication.cite
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  cite: prismic.RichTextField;

  /**
   * Date field in *Publication*
   *
   * - **Field Type**: Date
   * - **Placeholder**: *None*
   * - **API ID Path**: publication.date
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#date
   */
  date: prismic.DateField;

  /**
   * Optional Link field in *Publication*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: publication.optional_link
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  optional_link: prismic.LinkField;
}

/**
 * Publication document from Prismic
 *
 * - **API ID**: `publication`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type PublicationDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<
    Simplify<PublicationDocumentData>,
    "publication",
    Lang
  >;

type ResearchDocumentDataSlicesSlice = ThesisStudentSlice | CollaboratorSlice;

/**
 * Content for Research documents
 */
interface ResearchDocumentData {
  /**
   * Cover Image field in *Research*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: research.cover_image
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  cover_image: prismic.ImageField<never>;

  /**
   * Date field in *Research*
   *
   * - **Field Type**: Date
   * - **Placeholder**: *None*
   * - **API ID Path**: research.date
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#date
   */
  date: prismic.DateField;

  /**
   * Title field in *Research*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: research.title
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  title: prismic.KeyTextField;

  /**
   * Description field in *Research*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: research.description
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  description: prismic.RichTextField;

  /**
   * Optional Link field in *Research*
   *
   * - **Field Type**: Link to Media
   * - **Placeholder**: *None*
   * - **API ID Path**: research.optional_link
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  optional_link: prismic.LinkToMediaField;

  /**
   * Slice Zone field in *Research*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: research.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<ResearchDocumentDataSlicesSlice>;
}

/**
 * Research document from Prismic
 *
 * - **API ID**: `research`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type ResearchDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<
    Simplify<ResearchDocumentData>,
    "research",
    Lang
  >;

type ResearchPageDocumentDataSlicesSlice = ImageSlice;

/**
 * Content for Research Page documents
 */
interface ResearchPageDocumentData {
  /**
   * Slice Zone field in *Research Page*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: research_page.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<ResearchPageDocumentDataSlicesSlice> /**
   * Meta Description field in *Research Page*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: research_page.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */;
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *Research Page*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: research_page.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  meta_image: prismic.ImageField<never>;

  /**
   * Meta Title field in *Research Page*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: research_page.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_title: prismic.KeyTextField;
}

/**
 * Research Page document from Prismic
 *
 * - **API ID**: `research_page`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type ResearchPageDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<ResearchPageDocumentData>,
    "research_page",
    Lang
  >;

export type AllDocumentTypes =
  | FooterDocument
  | LandingPageDocument
  | PublicationDocument
  | ResearchDocument
  | ResearchPageDocument;

/**
 * Primary content in *Collaborator → Primary*
 */
export interface CollaboratorSliceDefaultPrimary {
  /**
   * Name field in *Collaborator → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: collaborator.primary.name
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  name: prismic.KeyTextField;
}

/**
 * Default variation for Collaborator Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type CollaboratorSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<CollaboratorSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *Collaborator*
 */
type CollaboratorSliceVariation = CollaboratorSliceDefault;

/**
 * Collaborator Shared Slice
 *
 * - **API ID**: `collaborator`
 * - **Description**: Collaborator
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type CollaboratorSlice = prismic.SharedSlice<
  "collaborator",
  CollaboratorSliceVariation
>;

/**
 * Primary content in *Gallery → Items*
 */
export interface ImageSliceDefaultItem {
  /**
   * Photo field in *Gallery → Items*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: image.items[].photo
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  photo: prismic.ImageField<never>;
}

/**
 * Default variation for Gallery Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ImageSliceDefault = prismic.SharedSliceVariation<
  "default",
  Record<string, never>,
  Simplify<ImageSliceDefaultItem>
>;

/**
 * Slice variation for *Gallery*
 */
type ImageSliceVariation = ImageSliceDefault;

/**
 * Gallery Shared Slice
 *
 * - **API ID**: `image`
 * - **Description**: Image
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ImageSlice = prismic.SharedSlice<"image", ImageSliceVariation>;

/**
 * Primary content in *PageDescription → Primary*
 */
export interface PageDescriptionSliceDefaultPrimary {
  /**
   * Description field in *PageDescription → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: page_description.primary.description
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  description: prismic.RichTextField;
}

/**
 * Default variation for PageDescription Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type PageDescriptionSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<PageDescriptionSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *PageDescription*
 */
type PageDescriptionSliceVariation = PageDescriptionSliceDefault;

/**
 * PageDescription Shared Slice
 *
 * - **API ID**: `page_description`
 * - **Description**: PageDescription
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type PageDescriptionSlice = prismic.SharedSlice<
  "page_description",
  PageDescriptionSliceVariation
>;

/**
 * Primary content in *ThesisStudent → Primary*
 */
export interface ThesisStudentSliceDefaultPrimary {
  /**
   * Name field in *ThesisStudent → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: thesis_student.primary.name
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  name: prismic.KeyTextField;
}

/**
 * Default variation for ThesisStudent Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ThesisStudentSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<ThesisStudentSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *ThesisStudent*
 */
type ThesisStudentSliceVariation = ThesisStudentSliceDefault;

/**
 * ThesisStudent Shared Slice
 *
 * - **API ID**: `thesis_student`
 * - **Description**: ThesisStudent
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ThesisStudentSlice = prismic.SharedSlice<
  "thesis_student",
  ThesisStudentSliceVariation
>;

/**
 * Primary content in *Headline → Primary*
 */
export interface TitleSliceDefaultPrimary {
  /**
   * Title field in *Headline → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: title.primary.title
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  title: prismic.RichTextField;

  /**
   * Description field in *Headline → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: title.primary.description
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  description: prismic.RichTextField;
}

/**
 * Primary content in *Headline → Items*
 */
export interface TitleSliceDefaultItem {
  /**
   * Photo field in *Headline → Items*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: title.items[].photo
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  photo: prismic.ImageField<never>;
}

/**
 * Default variation for Headline Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type TitleSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<TitleSliceDefaultPrimary>,
  Simplify<TitleSliceDefaultItem>
>;

/**
 * Slice variation for *Headline*
 */
type TitleSliceVariation = TitleSliceDefault;

/**
 * Headline Shared Slice
 *
 * - **API ID**: `title`
 * - **Description**: Title
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type TitleSlice = prismic.SharedSlice<"title", TitleSliceVariation>;

declare module "@prismicio/client" {
  interface CreateClient {
    (
      repositoryNameOrEndpoint: string,
      options?: prismic.ClientConfig,
    ): prismic.Client<AllDocumentTypes>;
  }

  namespace Content {
    export type {
      FooterDocument,
      FooterDocumentData,
      LandingPageDocument,
      LandingPageDocumentData,
      LandingPageDocumentDataSlicesSlice,
      PublicationDocument,
      PublicationDocumentData,
      ResearchDocument,
      ResearchDocumentData,
      ResearchDocumentDataSlicesSlice,
      ResearchPageDocument,
      ResearchPageDocumentData,
      ResearchPageDocumentDataSlicesSlice,
      AllDocumentTypes,
      CollaboratorSlice,
      CollaboratorSliceDefaultPrimary,
      CollaboratorSliceVariation,
      CollaboratorSliceDefault,
      ImageSlice,
      ImageSliceDefaultItem,
      ImageSliceVariation,
      ImageSliceDefault,
      PageDescriptionSlice,
      PageDescriptionSliceDefaultPrimary,
      PageDescriptionSliceVariation,
      PageDescriptionSliceDefault,
      ThesisStudentSlice,
      ThesisStudentSliceDefaultPrimary,
      ThesisStudentSliceVariation,
      ThesisStudentSliceDefault,
      TitleSlice,
      TitleSliceDefaultPrimary,
      TitleSliceDefaultItem,
      TitleSliceVariation,
      TitleSliceDefault,
    };
  }
}
