import "@/app/assets/global.css";
import { repositoryName } from '@/prismicio';
import { PrismicPreview } from '@prismicio/next';
import type { Metadata } from "next";
import { Inter, Quattrocento } from "next/font/google";
import Footer from "./components/footer";
import Header from "./components/header";
import { getDictionary } from "../dictionaries/dictionaries";

const inter = Inter({ subsets: ["latin"] });
const quattrocento = Quattrocento({
  weight:["400","700"],
  subsets: ['latin'],
  variable: '--font-quattrocento',
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
  params:{lang}
}: Readonly<{
  children: React.ReactNode;
  params:any
}>) {
  const langDictionary = await getDictionary(lang);
  return (
    <html lang={lang ?? 'en'} className={`${quattrocento.variable} font-serif`}>
      <body className={`${inter.className} antialiased`}>
        <main className="p-gap flex flex-col gap-gap max-w-screen-xl mx-auto">
          <Header
            langDictionary={langDictionary}
            lang={lang}
          />
          {children}
          <PrismicPreview repositoryName={repositoryName} />
          <Footer/>
        </main>
      </body>
    </html>
  );
}
