// Code generated by Slice Machine. DO NOT EDIT.

import dynamic from "next/dynamic";

export const components = {
  image: dynamic(() => import("./Image")),
  page_description: dynamic(() => import("./PageDescription")),
  title: dynamic(() => import("./Headline")),
};
